image:
  - Visual Studio 2017


environment:

  matrix:
    - arch: x64
      PYTHON: "C:\\Python37-x64"

platform:
  - x64
  
install:
  - cmd: mkdir C:\ninja-build
  - ps: (new-object net.webclient).DownloadFile('https://github.com/mesonbuild/cidata/raw/master/ninja.exe', 'C:\ninja-build\ninja.exe')
  - set CMAKE_MAKE_PROGRAM=ninja.exe
  - set CMAKE_TOOLCHAIN_FILE=C:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake
  # Print out dependency paths
  - cmd: echo Using Python at %PYTHON%
  # Add neccessary paths to PATH variable
  - cmd: set PATH=%cd%;C:\ninja-build;%PYTHON%;%PYTHON%\Scripts;%PATH%
  # Install meson the build tood
  - cmd: pip install meson
  # Install make because TBB uses it
  - choco install make
  
  - cd c:\tools\vcpkg
  # Update ports
  - git pull
  - # Update vcpkg
  - .\bootstrap-vcpkg.bat
  # Enable integration for Visual Studio/MSBuild
  - vcpkg integrate install
  - vcpkg install tbb
  
  # install conan the package manager
  #- cmd: pip install conan
  #- cmmd: conan user # Create the conan data directory
  #- cmd: conan install TBB/2019_U3@conan/stable
before_build:
  - cd C:\projects\hardwareIr

build_script:
  - cmd: echo Building on %arch% with %compiler%
  - cmd: meson --backend=ninja build
  - cmd: ninja -C build

test_script:
  - cmd: ninja -C build test


