image:
  - Visual Studio 2017

environment:

  matrix:
    - arch: x64
      compiler: msvc2017
      PYTHON: "C:\\Python37-x64"
      BOOST_ROOT: "C:\\Libraries\\boost_1_69_0"

platform:
  - x64
  
install:
  - cmd: mkdir C:\ninja-build
  - ps: (new-object net.webclient).DownloadFile('https://github.com/mesonbuild/cidata/raw/master/ninja.exe', 'C:\ninja-build\ninja.exe')
  # Print out dependency paths
  - cmd: echo Using Python at %PYTHON%
  - cmd: echo Using boost at %BOOST_ROOT%
  # Add neccessary paths to PATH variable
  - cmd: set PATH=%cd%;C:\ninja-build;%PYTHON%;%PYTHON%\Scripts;%PATH%
  # Install meson the build tood
  - cmd: pip install meson
    # Set up the build environment
  - cmd: if %compiler%==msvc2015 ( call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %arch% )
  - cmd: if %compiler%==msvc2017 ( call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %arch% )

before_build:
  - cd C:\projects\netlistDB

build_script:
  - cmd: echo Building on %arch% with %compiler%
  - cmd: meson --backend=ninja build
  - cmd: ninja -C build

test_script:
  - cmd: ninja -C build test

on_failure:
  - cmd: type C:\projects\netlistdb\build\meson-logs\meson-log.txt
  - cmd: dir C:\projects\netlistdb\build\meson-out\
  
