environment:

  matrix:
    - arch: x64
      compiler: msvc2017
      PYTHON: "C:\\Python37-x64"

platform:
  - x64
  
install:
  - cmd: mkdir C:\ninja-build
  - ps: (new-object net.webclient).DownloadFile('https://github.com/mesonbuild/cidata/raw/master/ninja.exe', 'C:\ninja-build\ninja.exe')
  #- cmd: if %compiler%==msvc2017 ( call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %arch% )
  # Print out dependency paths
  - cmd: echo Using Python at %PYTHON%
  # Add neccessary paths to PATH variable
  - cmd: set PATH=%cd%;C:\ninja-build;%PYTHON%;%PYTHON%\Scripts;%PATH%
  # Install meson
  - cmd: pip install meson

build_script:
  - cmd: echo Building on %arch% with %compiler%
  - cmd: meson --backend=ninja build
  - cmd: ninja -C build

test_script:
  - cmd: ninja -C build test


