dist: xenial
language: cpp
sudo: true
os: linux
cache:
  apt: true

# for meson
python:
- '3.6'

// https://github.com/AMS21/Andres-Standard-Library/blob/master/.travis.yml
matrix:
  include:
    - env: COMPILER=g++-7 BUILD=Debug
      compiler: gcc
      addons:
        apt:
          update: true
          sources:
            - sourceline: 'ppa:mhier/libboost-latest'
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - boost1.67
            - ninja-build
            - python3-pip
            - python3-setuptools
            - libtbb-dev
            - gcov

before_script:
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then export CXX=${COMPILER}; fi
  - sudo pip3 install meson
  - sudo pip3 install cpp-coveralls
  - mkdir build
  - meson build -Db_coverage=true
  - cd build

script: ninja && ninja test && ninja coverage

after_success:
  - coveralls --root . -E ".*_test.*"


